### ISSUE TITLE
Request body too large error during Simulate of install bundle

### ISSUE THREAD

**Issue by dckc** [DCFoundation/cosmos-proposal-builder#12]
@kbennett2000 and I were trying to upload a 4.7MB bundle using cosgov and we got **Bad status on response: 400**.

![image](https://github.com/DCFoundation/cosmos-proposal-builder/assets/150986/97a589e9-1e45-4bb9-9b2d-8033488f11c4)

Digging into the console, we found `{path: "/cosmos.tx.v1beta1.Service/Simulate",…}` in the request and `"error reading request body: http: request body too large"` in the response.

Something in the console showed that a `data` field was just over 2MB.

<details><summary>console log with Error#2: Bad status on response: 400</summary>
```
(TypeError#1)
error @ index-60743d00.js:40
index-60743d00.js:38 TypeError#1: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
nn @ index-60743d00.js:38
index-60743d00.js:40   at kt (https://cosgov.org/assets/index-60743d00.js:80:3887)
  at kt (https://cosgov.org/assets/index-60743d00.js:80:2304)
  at Object.Nb (https://cosgov.org/assets/index-60743d00.js:63:10464)
  at Tb (https://cosgov.org/assets/index-60743d00.js:63:10633)
  at Ub (https://cosgov.org/assets/index-60743d00.js:63:10699)
  at nf (https://cosgov.org/assets/index-60743d00.js:63:33610)
  at se$1 (https://cosgov.org/assets/index-60743d00.js:63:34087)
  at https://cosgov.org/assets/index-60743d00.js:63:39531
  at Rk (https://cosgov.org/assets/index-60743d00.js:66:40620)
  at Jb (https://cosgov.org/assets/index-60743d00.js:63:9554)
  at hd (https://cosgov.org/assets/index-60743d00.js:63:35514)
  at fd (https://cosgov.org/assets/index-60743d00.js:63:18583)
  at ed (https://cosgov.org/assets/index-60743d00.js:63:18335)
nn @ index-60743d00.js:40
localhost:26657/:1
       Failed to load resource: the server responded with a status of 400 (Bad Request)
index-60743d00.js:40 (Error#2)
error @ index-60743d00.js:40
index-60743d00.js:38 Error#2: Bad status on response: 400
nn @ index-60743d00.js:38
index-60743d00.js:40   at filterBadStatus (https://cosgov.org/assets/index-60743d00.js:69:15892)
  at async HttpClient.execute (https://cosgov.org/assets/index-60743d00.js:69:18884)
  at async Tendermint34Client.doCall (https://cosgov.org/assets/index-60743d00.js:69:65399)
  at async O1.queryAbci (https://cosgov.org/assets/index-60743d00.js:68:2123)
  at async Object.request (https://cosgov.org/assets/index-60743d00.js:68:3703)
  at async Object.simulate (https://cosgov.org/assets/index-60743d00.js:68:883048)
  at async dn.simulate (https://cosgov.org/assets/index-60743d00.js:69:112268)
  at async It (https://cosgov.org/assets/index-60743d00.js:106:85082)
  at async vt (https://cosgov.org/assets/index-60743d00.js:106:86059)
  ```
</details> 

<details><summary>Request body too large error from network tab</summary>

_please excuse the formatting_

```
{jsonrpc: "2.0", error: {code: -32600, message: "Invalid Request",…}}
error
:
{code: -32600, message: "Invalid Request",…}
code
:
-32600
data
:
"error reading request body: http: request body too large"
message
:
"Invalid Request"
jsonrpc
:
"2.0"
[3:33](https://agoricopco.slack.com/archives/D05N65T33U4/p1701380009299759)
{jsonrpc: "2.0", id: 969964688476, method: "abci_query",…}
id
:
969964688476
jsonrpc
:
"2.0"
method
:
"abci_query"
params
:
{path: "/cosmos.tx.v1beta1.Service/Simulate",…}
data
:
"12caac480af0ab480aecab480a212f61676f7269632e73776
path
:
"/cosmos.tx.v1beta1.Service/Simulate"
prove
:
false
```
</details>

**Comment by 0xpatrickdev** [comment]
> I suspect that an install-bundle transaction is getting base-64 encoded, taking it over the 1MB limit that typical RPC nodes use.

The logic is here: https://github.com/DCFoundation/cosmos-proposal-builder/blob/main/src/lib/compression.ts#L27-L38

- `blobToBase64` is checked in but not used (_was saving for future use with amino signing_)
- the encoding path is json string -> blob -> gzip blob -> uint8array

**Comment by dckc** [comment]
oops... that one is 1.7MB
this is 4+MB

[b1-6db2e93bb2382a520fc52832afa15ebabd6db98a1ae286562e78ba5ec622b87da76bfb34778ebf15e998084a4cc1b71f42ec45c4e2b5fba3bb3c9f86afef4a0e.json](https://github.com/DCFoundation/cosmos-proposal-builder/files/13518384/b1-6db2e93bb2382a520fc52832afa15ebabd6db98a1ae286562e78ba5ec622b87da76bfb34778ebf15e998084a4cc1b71f42ec45c4e2b5fba3bb3c9f86afef4a0e.json)

**Comment by dckc** [comment]
We diagnosed this today: even when compressed, the 4.7MB bundle was over the 1MB threshold that RPC servers default to for max body size:

 - https://github.com/Agoric/agoric-sdk/issues/8621
